### ISSUE TITLE
Input length must be multiple of 16 when decrypting with padded cipher

### ISSUE THREAD

**Issue by fvalle1** [Flo354/SafariFormValuesDecryptor#2]
I'm trying to decrypt my Fill Values file. but I receive

> Exception in thread "main" javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
	at java.base/com.sun.crypto.provider.CipherCore.prepareInputBuffer(CipherCore.java:1005)
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:848)
	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
	at com.flo354.decrypt.safari.formvalues.FormValueDecryptor.decrypt(FormValueDecryptor.java:39)
	at com.flo354.decrypt.safari.formvalues.FormValueDecryptor.main(FormValueDecryptor.java:56)

Any idea of what can be the issue be?

Thank you

**Comment by Flo354** [comment]
Hello there,

It is related to #1

Actually, the tool I wrote is usable for old version of MacOS.

We discovered in #1 that at some point, Apple changed the encryption process. Unfortunately, I don't have the time to dig into this as it requires some reverse engineering.

If at some point I need the feature for new versions of MacOS I will try to implement it.

Otherwise, if you or someone has the knowledge to do it, pull requests are most welcomed!

**Comment by bernsteining** [comment]
Hi,

For which versions of macOS & Safari did your tool work correctly?

I'm currently trying with different Form Values from different versions and I'm getting the same error as above. (macOS 10.7 & 10.11)

Also, an example of working Form Values & Password would be awesome.

Nice project anyway!

**Comment by Flo354** [comment]
Hello there,

So I remembered that I did this program for a Form Value that was on a MacOS 10.7.
So it should work on MacOS 10.7, but to be honest, I used that project a single time, so I don't really remember how I used it
